# Generated by Django 5.1 on 2024-08-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
